In [7]:
math.sqrt(3)

1.7320508075688772

In [5]:
import numpy as np
import math

In [8]:
value=np.zeros([8,10])
value[4][5]=100

In [9]:
discount=0.8
a=['w','a','s','d']

In [ ]:
start_row=0
start_column=0
update=100
diff=np.abs(value[start_row][start_column]-update)
while diff>0.001:
    vv=[]
    for action in a:
        if action=='w':
            row=start_row-1
            column=start_column
            if row<0:
                rewards=-10
                row=start_row
            else:
                rewards=0
            vv.append(rewards+discount*value[row][column])
        elif action=='s':
            row=start_row+1
            column=start_column
            if row>=8:
                rewards=-10
                row=start_row
            else:
                rewards=0
            vv.append(rewards+discount*value[row][column])
        elif action=='a':
            column=start_column-1
            row=start_row
            if column<0:
                rewards=-10
                column=start_column
            else:
                rewards=0
            vv.append(rewards+discount*value[row][column])
        elif action=='d':
            column=start_column+1
            row=start_row
            if column>=10:
                rewards=-10
                row=start_row
            else:
                rewards=0
            vv.append(rewards+discount*value[row][column])
        value[start_row][start_column]=np.max(vv)

In [15]:
start_row=3
start_column=5
update=100
diff=np.abs(value[start_row][start_column]-update)
vv=[]
for action in a:
    if action=='w':
        row=start_row-1
        column=start_column
        if row<0:
            rewards=-10
            row=start_row
        else:
            rewards=0
        vv.append(rewards+discount*value[row][column])
    elif action=='s':
        row=start_row+1
        column=start_column
        if row>=8:
            rewards=-10
            row=start_row
        else:
            rewards=0
        vv.append(rewards+discount*value[row][column])
    elif action=='a':
        column=start_column-1
        row=start_row
        if column<0:
            rewards=-10
            column=start_column
        else:
            rewards=0
        vv.append(rewards+discount*value[row][column])
    elif action=='d':
        column=start_column+1
        row=start_row
        if column>=10:
            rewards=-10
            row=start_row
        else:
            rewards=0
        vv.append(rewards+discount*value[row][column])
    value[start_row][start_column]=np.max(vv)
    
print(value,vv)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  80. 100.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]] [0.0, 0.0, 80.0, 0.0]


In [ ]:
for i in range(8):
    for j in range(10):
        if a=='w':
            i_new=i-1
            if i_new<0:
                